import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-cover bg-no-repeat bg-pretty-image bg-fixed max-h-screen max-w-screen">
            <main className="overflow-scroll m-auto my-[6em] rounded-xl bg-white/70 p-24 w-[80%] backdrop-blur">
              {children}
            </main>
        </body>
    </html>
  )
}
